//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planet.ServiceForm.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class firma_isim
    {
        public int id { get; set; }
        public string firma_isimi { get; set; }
    }
}
