//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planet.ServiceForm.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class usertbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usertbl()
        {
            this.firmatbls = new HashSet<firmatbl>();
            this.formtbls = new HashSet<formtbl>();
        }
    
        public int id { get; set; }
        public string user_ad { get; set; }
        public string user_soyad { get; set; }
        public string user_sifre { get; set; }
        public string user_mail { get; set; }
        public string user_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<firmatbl> firmatbls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<formtbl> formtbls { get; set; }
    }
}
